### ISSUE TITLE
MQL Idx function spins on out-of-bonds

### ISSUE THREAD

**Issue by YairMarcowMavenomics** [Mavenomics/MavenWorks#40] opened 2019-11-04 22:04 UTC
Seems like an out-of-bounds attempt to acces >= len leaves queries spinning forever:

```
set @v = StringVector( 'a', 'b', 'c' )

SELECT
	idx(@v, -1) as ThisGivesAReasonableError,
	idx(@v, 2) as ThisReturnsB,
    idx( @v, 3) as ThisSpinsForever
FROM
    dual
```

**Comment by quigleyj-mavenomics** [comment] 2019-11-05 02:15
This particular issue was fixed in https://github.com/Mavenomics/MavenWorks/commit/6c3c9e454dcb1f09e3dbb85c42d0f7e2f4ebd77e, and I forgot to x-ref it.

Root cause is https://github.com/Mavenomics/MavenWorks/projects/1#card-28723793

**Closed by quigleyj-mavenomics** 2019-11-05 02:15 UTC
